
# Enhanced Chat - Configuration File

EnhancedChat:

    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #
    #   Database connection arguments
    #
    #   Those options are fully customizable. If you are not using MySQL, look on internet
    #   for other engines with these keywords -> "hibernate", "dialect","(your database engine)"
    # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- # ---- #

    # Database connection

    database:
        dialect:        MySQL8Dialect
        address:        localhost
        port:           3306
        database:       enhanced_chat

        username:       root
        password:       ""

    hibernate:
        show_sql:       false
        format_sql:     true
        sql_comments:   true

Security:

    max_weight: 18

Chat:

    type:

        # World chat - Enables chat per world
        World:  true        # [ true / false ] if false chat will be global.

        # Local chat - Restrict chat to range
        Local:
            enable: true    # [ true / false ]
            range: 15       # Range in blocks

        # Private chat - Enables private chat [WARNING! Private chat is not under surveillance.]
        Private: false      # [ true / false ]

        # Character chat - Enables character chat [ It's more likely for Role-Play ]
        #   Enables commands:
        #       - /me
        #       - /do
        Character: false      # [ true / false ]

    Listener:

        AntiCap:
            enabled:        true    # [ true / false ]

        AntiFlood:
            enabled:        true    # [ true / false ]
            max_characters: 5       # Maximum amount of the same letters in a row

        AntiSpam:
            enabled:        true    # [ true / false ]
            max_messages:   4       # Maximum messages in time frame
            time_frame:     6       # Time frame in seconds
            mute_duration:  20      # Mute duration in seconds

            Warning:
                weight:     2       # Weight of the warning alert